draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: |-
    svg {
      background-color: white;
      background: white;
    }

    rect.key {
          fill: transparent;  /* light gray */
      }

      /* color accent for held keys (keys that activate layers) */
      rect.held, rect.combo.held {
          fill: #fdd;  /* light pink/red */
      }

      /* ghost keys (optional) */
      rect.ghost, rect.combo.ghost {
          stroke-dasharray: 4, 4;  /* dashed border */
          stroke-width: 2;
      }
  footer_text: ''
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: â–½
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    N1:
      tap: '1'
      shifted: '!'
    N2:
      tap: '2'
      shifted: '@'
    N3:
      tap: '3'
      shifted: '#'
    N4:
      tap: '4'
      shield: '$'
    N5:
      tap: '5'
      shifted: '%'
    N6:
      tap: '6'
      shifted: '^'
    N7:
      tap: '7'
      shifted: '&'
    N8:
      tap: '8'
      shifted: '*'
    N9:
      tap: '9'
      shifted: (
    N0:
      tap: '0'
      shifted: )
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: '='
      shifted: '+'
    PLUS: +
    MINUS:
      tap: '-'
      shifted: _
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH:
      tap: /
      shifted: '?'
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH:
      tap: \
      shifted: '|'
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI:
      tap: ;
      shifted: ':'
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT:
      tap: ''''
      shifted: '"'
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA:
      tap: ','
      shifted: <
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT:
      tap: .
      shifted: '>'
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT:
      tap: '['
      shifted: '{'
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT:
      tap: ']'
      shifted: '}'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE:
      tap: '`'
      shifted: '~'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos: {}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
